- README.md
Pull Request to merge readme to develop for completion of this weeks tasks.
> Readme to Develop

- Controller.py
- Diagram.py
- Entity.py
- Relation.py
Add basic diagram, entity and relation files
> Add basic diagram, entity and relation files

- CustomExceptions.py
- Diagram.py
- DiagramTest.py
- Entity.py
- Relation.py
Custom Exceptions
- Added Entity Not Found Exception
- Made exception documentation more consistent
Diagram
- Made file more consistent by referring to "entity" rather than "class/entity"
- Added rename, delete, and list entity methods (List was needed for test implementation)
**- IMPORTANT! Within the deleteEntity method are two method calls relation.contains() and deleteRelations(). These methods are defined, NOT implemented**
DiagramTest
- Successful testing us the Test classes
**- IMPORTANT! addEntity, and rename have been tested BUT deleteEntity relies on implmentation of Relation class**
Entity
- Created setName() used by renameEntity()
- Refactored code so that constructor calls this method as well
Relation
- Added dummy method called by deleteEntity()
> Implemented Rename and Delete

- CustomParser.py
Blank files with light documentation, for use in near future. Need to discuss more with group how to best handle the parser.
> Initial Parser Commits

- CustomExceptions.py
- CustomParser.py
- Test.py
- parserTest.py
- Updated the documentation in Test.py to comply with standards
- Added basic alphanumeric input checking to the parser 
- laid out basic structure in the parser
- added three new errors to CustomExceptions for the parser:
- CommandNotFoundError - user has entered an invalid command
- InvalidArgumentError - user has entered an invalid arg (not alphanumeric)
- InvalidFlagError - user has entered an invalid flag (the things that come after the hyphens)
> Parser Groundwork and Test Documentation

- CustomExceptions.py
- Diagram.py
- DiagramTest.py
- Relation.py
Relation constructor, getters, to string, tests for relation.
> Base Relation functionality

- CustomExceptions.py
- Diagram.py
- DiagramTest.py
- Entity.py
- Relation.py
- Set relation methods to initially take strings and after validation, pass Entity objects to the Relation
- Implemented deleteEntity to remove both the entity and the associated relations, confirmations before calling this method should be done in the controller
- Fixed CustomException class which had part of a method deleted
- Re-arranged Custom Exceptions based on associated type
- Modified the relation method testing to match aforementioned changes
- Added contains method in the relation class for easily checking both the source and destination in one call
- Added __str__ method for entity
- Created a print relations method as well for deleteEntity testing
- Created tests for deleteEntity
- Ensured all existing Diagram Tests are passing
> Modified relation methods / Implemented deleteEntity

- Relation.py
quick fix to make sure develop can actually be run.
> Fixed indentation error in Relation

- Controller.py
- Entity.py
Added commands for:
- addAttribute
- deleteAttributes
- renameAttributes
> Added att command

- Help.py
Changed the help menu to reflect the implementations found in the parser.
> Help Menu Updates

- Controller.py
- Diagram.py
Added opt param to deal with it being passed by controller (we can clean it up later)
Changed the name of the one list function form 'c' to 'cd'. Either needs to be before the first 'c' or a different name.
> Added list functions and connected to controller

- Controller.py
- Diagram.py
- Entity.py
- Relation.py
No functional changes. Just getting things to a similar standard and cleaning up some comments.
> Formatting

- Controller.py
- CustomExceptions.py
- Input.py
- Output.py
- Serializer.py
- main.py
Add more exceptions for all kinds of errors that will happen in Read/Write files and Save/Load files
> Update error handling of Serializer and Input/Output

- README.md
- Serializer.py
- main.py
- testDiagram.py
> Debug mode

- Controller.py
- test/auto_test.py
- test/auto_test_list.txt
- test/save_input.txt
Fix save/load bugs.
Integration test framwork.
> Test save/load

- Controller.py
- CustomExceptions.py
- Diagram.py
- Entity.py
- Messages for ValueError and pop error are now prettier
- get_entity now throws the expected exception when the entity requested doesn't exist
- Messages when invalid argument counts were input now tell the user how many args were expected vs given.
- Removed a default parameter that would in very rare occasions break the parser
- Documentation updates
> bugfixes and error handling

- Help.py
Better descriptions, view suggestion, blurb at top.
> Updated Help.Py

- README.md
UPdate readMe to add steps for macOS
> Updated readME for macOS

- Controller.py
> Fix quit with save

- main.py
- src/umleditor/mvc_controller/cli_controller.py
- src/umleditor/mvc_controller/controller.py
- src/umleditor/mvc_controller/gui_controller.py
- GUI controller now inherits from controller
- GUI controller named better
- Minor CLI Syntax updates
- main now imports according to renamed files
> Name Changes and GUI Controller Update

- src/umleditor/mvc_model/diagram.py
- src/umleditor/mvc_model/entity.py
Relation changes are not functional, so I did not touch those.
I did not see functionality to actually add Params to the diagram, but the logic should work.
> List functionality working based on current implementations.

- src/test/test_relation.py
- src/umleditor/mvc_model/custom_exceptions.py
Added Pytest for relation.
testDiagram
> Updated pytest for relationship

- main.py
- src/umleditor/mvc_view/gui_view/class_card.py
- src/umleditor/mvc_view/gui_view/uml.ui
- src/umleditor/mvc_view/gui_view/view_GUI.py
- Escape now deletes the given row if the data has yet to be entered into the diagram
- If editing an existing row and escape is hit, the row returns to its original state, no requests to diagram are made
- Application now has a min size of 850x850
- Application now has a way of setting card spawn limits (currently set to 20)
- Error message will appear if over max spawns
- Application can be expanded best the min size for more room (although 850, will fit the current max size without expanding)
-
> Fixed Escape and Added card spawning/screen size changes

- src/test/test_diagram.py
- src/test/test_entity.py
- src/test/test_imports.py
- src/test/test_uml_method.py
Couple additions, Updated test_diagram to work with Pytest. Reorganized the import tests and added one.
> Building tests

- src/umleditor/mvc_controller/gui_controller.py
- src/umleditor/mvc_view/gui_view/class_card.py
- src/umleditor/mvc_view/gui_view/view_GUI.py
Added delete class functionality
> Add delete functionality to GUI controller and view

- src/umleditor/mvc_controller/gui_controller.py
- src/umleditor/mvc_view/gui_view/class_card.py
> Added rename functionality

- README.md
- main.py
Switch debug mode option from "-O" to "debug".
Cleanup main()
> Cleanup main.py and update readme

- setup.py
- src/umleditor/mvc_controller/GUIV2_controller.py
- src/umleditor/mvc_model/diagram.py
- src/umleditor/mvc_view/gui_view/gui_lambda/GUIV2.py
- src/umleditor/mvc_view/gui_view/gui_lambda/GUIV2_class_card.py
They work, nothing else does, but they do
> Classes work now

- src/umleditor/mvc_controller/serializer.py
- src/umleditor/mvc_model/entity.py
> Load and save

- main.py
> Fixed GUI Terminal

- src/test/test_entity.py
- src/test/test_serializer.py
- src/umleditor/mvc_controller/controller.py
- src/umleditor/mvc_controller/serializer.py
- src/umleditor/mvc_controller/uml_parser.py
- src/umleditor/mvc_model/diagram.py
- src/umleditor/mvc_model/entity.py
Parameters Fixed (it will only take parameters name).
> Parameters Fixed (it will only take parameters name).

- src/umleditor/mvc_model/custom_exceptions.py
- src/umleditor/mvc_model/entity.py
> Add entity fixed

- src/umleditor/mvc_model/custom_exceptions.py
- src/umleditor/mvc_model/entity.py
Documentation updated in entity.py and custom_exceptions.py.
> Documentation updated in entity.py and custom_exceptions.py.

- src/umleditor/mvc_controller/serializer.py
- src/umleditor/mvc_model/diagram.py
- src/umleditor/mvc_model/entity.py
- src/umleditor/mvc_view/gui_view/__init__.py
- src/umleditor/mvc_view/gui_view/gui_lambda/GUIV2.py
- src/umleditor/mvc_view/gui_view/gui_lambda/class_card_revamp.py
- src/umleditor/mvc_view/gui_view/gui_lambda/diagram_area.py
Reverts mucsci-students/2024sp-420-PythonA#247
> Revert "Locations"

- src/umleditor/mvc_controller/uml_parser.py
> Validation Error solved
